import { Person } from '../data/entities/person';

export let PEOPLE: Person[] = [
    { id: 1, name: 'Mihai Georgescu', position: 'Information Technology Manager', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'mihai_georgescu.png' },
    { id: 2, name: 'Valentin Stroe', position: 'Development Team Leader', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'valentin_stroe.png' },
    { id: 3, name: 'Cosmin Pîrlitu', position: 'Software Development Engineer', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'cosmin_pirlitu.png' },
    { id: 4, name: 'Razvan Bondei', position: 'Software Configuration Manager', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'razvan_bondei.png' },
    { id: 5, name: 'Camelia Damian', position: 'Software Business Analyst', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'camelia_damian.png' },
    { id: 6, name: 'Patryk Białek', position: 'UX Designer', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'patryk_bialek.png' },
    { id: 7, name: 'Ioana Atanasiu', position: 'Business Analyst Team Leader', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'ioana_atanasiu.png' },
    { id: 8, name: 'Bogdan Virjoghe', position: 'Software Development Engineer', workbio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', homebio: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nulla numquam quae iste temporibus nihil dolore, ut omnis minus nam sed facilis, facere illum rem aspernatur consequuntur atque voluptatem beatae!', photo: 'bogdan_virjoghe.png' }
];

/*
 * Copyright 2016 Medicover Group IT R&D. All Rights Reserved.
*/